name: Generate and Deploy Documentation

on:
  pull_request:
    types: [closed, merged]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Generate java doc
        run: mvn -B javadoc:javadoc

      - name: deploy github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GIT_HICH }}
          publish_dir: ./target/reports/apidocs